SELECT DISTINCT

	FLAN.CODCOLIGADA AS 'idmantenedora'
,	FLAN.CODFILIAL AS 'idies'
,	SMATRICPL.IDPERLET AS 'codletivo'
,	FLAN.IDLAN AS 'idlancamento'
,	SCONTRATO.CODCONTRATO AS 'idcontrato'
,	SCURSO.CODCURSO AS 'idcurso'
,	SHABILITACAOALUNO.CODCAMPUS AS 'idunidade'
,	FLAN.CODTDO AS 'idservico'
,	FLAN.PARCELA AS 'numparcela'
,	SALUNO.RA AS 'idaluno'
,	PESSOAALUNO.NOME AS 'nomealuno'
,	FCFO.CODCFO AS 'idrespfin'
,	FCFO.NOMEFANTASIA AS 'nomrespfin'
,	FLAN.DATAVENCIMENTO AS 'datventit'
,	YEAR(FLAN.DATAVENCIMENTO) AS 'anoventit'
,	MONTH(FLAN.DATAVENCIMENTO) AS 'mesventit'
,	FLAN.DATABAIXA AS 'datpagtit'
,	YEAR(FLAN.DATABAIXA) AS 'anopagtit'
,	MONTH(FLAN.DATABAIXA) AS 'mespagtit'
,	FLAN.VALORORIGINAL AS 'vlrbruto'
,	FLANBAIXA.VALORDESCONTO AS 'vlrdesconto'
,	FLANBAIXA.VALORMULTA AS 'vlrmulta'
,	FLANBAIXA.VALORJUROS AS 'vlrjuros'
,	BOLSALAN.VALORBOLSA AS 'vlrbolsa'
,	(FLAN.VALORORIGINAL - BOLSALAN.VALORBOLSA) AS 'vlrliquido'
,	(FLANBAIXA.VALORMULTA + FLANBAIXA.VALORJUROS) 'vlratraso'
,	FLANBAIXA.VALORBAIXA AS 'vlrpago'

	
,	(CASE 
		WHEN STATUSLAN = 0 THEN 'EM ABERTO'
		WHEN STATUSLAN = 1 THEN 'BAIXADO'
		WHEN STATUSLAN = 2 THEN 'CANCELADO'
		WHEN STATUSLAN = 3 THEN 'BAIXADO POR ACORDO'
		WHEN STATUSLAN = 4 THEN 'BAIXA PARCIAL'
	END) AS 'ststitulo'


	FROM [CORPORERM_TESTE].dbo.FLAN (NOLOCK)
	
	INNER JOIN [CORPORERM_TESTE].dbo.FCFO (NOLOCK)
	ON FLAN.CODCOLCFO = FCFO.CODCOLIGADA
	AND FLAN.CODCFO = FCFO.CODCFO
		
	LEFT JOIN [CORPORERM_TESTE].dbo.SLAN (NOLOCK)
	ON SLAN.CODCOLIGADA = FLAN.CODCOLIGADA
	AND SLAN.IDLAN = FLAN.IDLAN
	   
	LEFT JOIN [CORPORERM_TESTE].dbo.SPARCELA (NOLOCK)
	ON SPARCELA.CODCOLIGADA = SLAN.CODCOLIGADA
	AND SPARCELA.IDPARCELA = SLAN.IDPARCELA
	   
	LEFT JOIN [CORPORERM_TESTE].dbo.SCONTRATO (NOLOCK)
	ON SCONTRATO.CODCOLIGADA = SPARCELA.CODCOLIGADA
	AND SCONTRATO.IDPERLET = SPARCELA.IDPERLET
	AND SCONTRATO.CODCONTRATO = SPARCELA.CODCONTRATO
	AND SCONTRATO.RA = SPARCELA.RA

	LEFT JOIN [CORPORERM_TESTE].dbo.SALUNO (NOLOCK)
	ON SALUNO.CODCOLIGADA = SCONTRATO.CODCOLIGADA
	AND SALUNO.RA = SCONTRATO.RA
	   
	LEFT JOIN [CORPORERM_TESTE].dbo.PESSOAALUNO (NOLOCK)
	ON PESSOAALUNO.CODIGO = SALUNO.CODPESSOA

	LEFT JOIN (	SELECT DISTINCT
					IDLAN
				,	SUM(VALORBAIXA) VALORBAIXA
				,	SUM(VALORMULTA) VALORMULTA
				,	SUM(VALORJUROS) VALORJUROS
				,	SUM(VALOROP8) VALOROP8
				,	DATAVENCIMENTOLANCAMENTO
				,	SUM(VALORDESCONTO) VALORDESCONTO

					FROM [CORPORERM_TESTE].dbo.FLANBAIXA
	
					WHERE 1=1
					AND CODCOLIGADA = 1
					AND YEAR(DATAVENCIMENTOLANCAMENTO) >= 2022
					AND VALORPERDAFINANCEIRA = 0
					AND STATUS = 0
	
					GROUP BY IDLAN, DATAVENCIMENTOLANCAMENTO) FLANBAIXA
	ON FLANBAIXA.IDLAN = FLAN.IDLAN

	LEFT JOIN [CORPORERM_TESTE].dbo.SMATRICPL (NOLOCK)
	ON SMATRICPL.CODCOLIGADA = SCONTRATO.CODCOLIGADA
	AND SMATRICPL.RA = SALUNO.RA
	AND SMATRICPL.IDPERLET = SCONTRATO.IDPERLET
	AND SMATRICPL.IDHABILITACAOFILIAL = SCONTRATO.IDHABILITACAOFILIAL
	

	LEFT JOIN [CORPORERM_TESTE].dbo.SMATRICULA (NOLOCK)
	ON SMATRICULA.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SMATRICULA.IDPERLET = SMATRICPL.IDPERLET
	AND SMATRICULA.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	AND SMATRICULA.RA = SMATRICPL.RA
	 
	LEFT JOIN [CORPORERM_TESTE].dbo.SHABILITACAOFILIAL (NOLOCK)
	ON SHABILITACAOFILIAL.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SHABILITACAOFILIAL.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	-- #FILTRO: Desconsiderar "11 = UCB - REGISTRO DE DIPLOMAS DE OUTRAS IES"
	AND SHABILITACAOFILIAL.CODTIPOCURSO <> 11

	LEFT JOIN [CORPORERM_TESTE].dbo.SCURSO (NOLOCK)
	ON SCURSO.CODCOLIGADA = SHABILITACAOFILIAL.CODCOLIGADA
	AND SCURSO.CODCURSO = SHABILITACAOFILIAL.CODCURSO

	INNER JOIN [CORPORERM_TESTE].dbo.SHABILITACAOALUNO (NOLOCK)
	ON SHABILITACAOALUNO.CODCOLIGADA = SALUNO.CODCOLIGADA
	AND SHABILITACAOALUNO.RA = SALUNO.RA
	AND SHABILITACAOALUNO.CODCOLIGADA = SMATRICPL.CODCOLIGADA
	AND SHABILITACAOALUNO.IDHABILITACAOFILIAL = SMATRICPL.IDHABILITACAOFILIAL
	AND SHABILITACAOALUNO.RA = SMATRICPL.RA

	LEFT JOIN (SELECT DISTINCT
					FLAN.IDLAN
				,	SUM(SBOLSALAN.VALOR) AS VALORBOLSA

					FROM [CORPORERM_TESTE].dbo.FLAN (NOLOCK)
					INNER JOIN SBOLSALAN
					ON FLAN.CODCOLIGADA = SBOLSALAN.CODCOLIGADA
					AND FLAN.IDLAN = SBOLSALAN.IDLAN

					INNER JOIN SBOLSA (NOLOCK)
					ON SBOLSA.CODCOLIGADA = SBOLSALAN.CODCOLIGADA 
					AND SBOLSA.CODBOLSA = SBOLSALAN.CODBOLSA 

					WHERE 1=1
					AND SBOLSA.ATIVA='S'
					AND YEAR(FLAN.DATAVENCIMENTO) >= 2022
					GROUP BY FLAN.IDLAN, FLAN.DATAVENCIMENTO) BOLSALAN
	ON FLAN.IDLAN = BOLSALAN.IDLAN
	

	WHERE 1=1
	AND FLAN.CODCOLIGADA = 1
	AND FLAN.PAGREC = 1
	AND YEAR(FLAN.DATAVENCIMENTO) >= 2022
	AND FLAN.CODTDO IN ('MEN', 'PEU M', 'PEU F', 'PRAVALER', 'FUNDACR M', 'FUNDACR F', 'REM')
	
	/* Desconsiderar STATUS TRANSITÓRIOS - operacionais */
	AND SHABILITACAOALUNO.CODSTATUS NOT IN
( '545','592','719','814','439','689','688','813','370','604','717','718','97','372','697','486','543','149','483','487','544','482','152','287','484','517','5','13','419','420')
